CREATE TABLE `video_platform_channel` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `device_id` bigint NOT NULL COMMENT '关联设备主表ID',
  `instance_key` varchar(100) NOT NULL COMMENT '平台实例唯一标识',
  `platform_device_id` varchar(100) NOT NULL COMMENT '平台侧设备ID',
  `channel_id` varchar(100) NOT NULL COMMENT '通道ID（平台侧唯一标识）',
  `channel_name` varchar(200) DEFAULT NULL COMMENT '通道名称',
  `channel_status` varchar(50) DEFAULT NULL COMMENT '通道状态: online/offline',
  `channel_type` varchar(50) DEFAULT NULL COMMENT '通道类型: analog/digital/virtual',
  `parent_id` varchar(100) DEFAULT NULL COMMENT '父通道ID（级联场景）',
  `manufacturer` varchar(100) DEFAULT NULL COMMENT '通道厂商',
  `model` varchar(100) DEFAULT NULL COMMENT '通道型号',
  `owner` varchar(100) DEFAULT NULL COMMENT '通道所有者',
  `civil_code` varchar(100) DEFAULT NULL COMMENT '行政区划',
  `address` varchar(200) DEFAULT NULL COMMENT '安装地址',
  `parental` int DEFAULT '0' COMMENT '是否有子设备: 0-否 1-是',
  `safety_way` int DEFAULT NULL COMMENT '信令安全模式',
  `register_way` int DEFAULT NULL COMMENT '注册方式',
  `secrecy` int DEFAULT NULL COMMENT '保密属性',
  `ip_address` varchar(50) DEFAULT NULL COMMENT '通道IP地址',
  `port` int DEFAULT NULL COMMENT '通道端口',
  `longitude` varchar(50) DEFAULT NULL COMMENT '经度',
  `latitude` varchar(50) DEFAULT NULL COMMENT '纬度',
  `ptz_type` int DEFAULT '0' COMMENT '云台类型: 0-不支持 1-球机 2-半球 3-固定枪机 4-遥控枪机',
  `position_type` int DEFAULT NULL COMMENT '位置类型',
  `stream_id` varchar(100) DEFAULT NULL COMMENT 'WVP流ID',
  `gb_stream_id` varchar(100) DEFAULT NULL COMMENT 'WVP国标流ID',
  `has_audio` tinyint DEFAULT '0' COMMENT 'WVP是否有音频',
  `camera_index_code` varchar(100) DEFAULT NULL COMMENT '海康摄像机唯一标识码(用于抓图/预览)',
  `channel_no` varchar(20) DEFAULT NULL COMMENT '海康通道号',
  `camera_type` int DEFAULT NULL COMMENT '海康摄像机类型: 0-枪机/1-球机/2-半球',
  `ptz` tinyint DEFAULT NULL COMMENT '海康是否支持云台: 0-否/1-是',
  `capability_set` varchar(100) DEFAULT NULL COMMENT '海康通道能力集编码',
  `install_location` varchar(200) DEFAULT NULL COMMENT '海康安装位置',
  `channel_code` varchar(100) DEFAULT NULL COMMENT '大华通道编码',
  `channel_seq` int DEFAULT NULL COMMENT '大华通道序号',
  `encode_format` varchar(50) DEFAULT NULL COMMENT '大华编码格式',
  `resolution` varchar(50) DEFAULT NULL COMMENT '大华分辨率',
  `capabilities` text COMMENT '通道能力集（JSON）: 录像/抓图/对讲/报警等',
  `stream_config` text COMMENT '流配置（JSON）: 主码流/子码流参数',
  `ext_field1` varchar(500) DEFAULT NULL COMMENT '扩展字段1',
  `ext_field2` varchar(500) DEFAULT NULL COMMENT '扩展字段2',
  `ext_field3` text COMMENT '扩展字段3（JSON）',
  `enabled` tinyint DEFAULT '1' COMMENT '是否启用：0-禁用，1-启用',
  `create_id` varchar(100) DEFAULT NULL COMMENT '创建者ID',
  `update_id` varchar(100) DEFAULT NULL COMMENT '更新者ID',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_device_channel` (`device_id`,`channel_id`),
  UNIQUE KEY `uk_instance_channel` (`instance_key`,`channel_id`,`parent_id`) USING BTREE,
  KEY `idx_instance_key` (`instance_key`),
  KEY `idx_platform_device_id` (`platform_device_id`),
  KEY `idx_channel_status` (`channel_status`),
  KEY `idx_camera_index_code` (`camera_index_code`),
  KEY `idx_channel_code` (`channel_code`),
  KEY `idx_ptz_type` (`ptz_type`),
  CONSTRAINT `fk_video_channel_device` FOREIGN KEY (`device_id`) REFERENCES `video_platform_device` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='视频平台通道表';

CREATE TABLE `video_platform_device` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `instance_key` varchar(100) NOT NULL COMMENT '平台实例唯一标识',
  `device_id` varchar(100) NOT NULL COMMENT '设备ID（平台侧唯一标识）',
  `device_name` varchar(200) DEFAULT NULL COMMENT '设备名称',
  `device_status` varchar(50) DEFAULT NULL COMMENT '设备状态: online/offline/1/0等',
  `device_model` varchar(100) DEFAULT NULL COMMENT '设备型号',
  `device_ip` varchar(50) DEFAULT NULL COMMENT '设备IP地址',
  `device_port` int DEFAULT NULL COMMENT '设备端口',
  `manufacturer` varchar(100) DEFAULT NULL COMMENT '设备厂商',
  `org_id` varchar(100) DEFAULT NULL COMMENT '所属组织ID',
  `org_name` varchar(200) DEFAULT NULL COMMENT '所属组织名称',
  `gps_x` varchar(50) DEFAULT NULL COMMENT '经度（longitude）',
  `gps_y` varchar(50) DEFAULT NULL COMMENT '纬度（latitude）',
  `gps_z` varchar(50) DEFAULT NULL COMMENT 'Z轴高度（altitude）',
  `configuration` text COMMENT '设备配置（JSON）包含channelList、能力集等公共扩展信息',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注说明',
  `enabled` tinyint DEFAULT '1' COMMENT '是否启用：0-禁用，1-启用',
  `create_id` varchar(100) DEFAULT NULL COMMENT '创建者ID',
  `update_id` varchar(100) DEFAULT NULL COMMENT '更新者ID',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_instance_device` (`instance_key`,`device_id`),
  KEY `idx_instance_key` (`instance_key`),
  KEY `idx_device_status` (`device_status`),
  KEY `idx_org_id` (`org_id`),
  KEY `idx_enabled` (`enabled`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='视频平台设备主表';

CREATE TABLE `video_platform_device_ext` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `device_id` bigint NOT NULL COMMENT '关联主表设备ID',
  `instance_key` varchar(100) NOT NULL COMMENT '平台实例唯一标识',
  `platform_device_id` varchar(100) NOT NULL COMMENT '平台侧设备ID',
  `charset` varchar(20) DEFAULT NULL COMMENT 'WVP字符集: GB2312/UTF-8',
  `transport` varchar(20) DEFAULT NULL COMMENT 'WVP传输协议: UDP/TCP',
  `stream_mode` varchar(50) DEFAULT NULL COMMENT 'WVP流模式: TCP-ACTIVE/TCP-PASSIVE/UDP',
  `host_address` varchar(100) DEFAULT NULL COMMENT 'WVP主机地址',
  `expires` int DEFAULT NULL COMMENT 'WVP注册有效期(秒)',
  `keepalive_time` datetime DEFAULT NULL COMMENT 'WVP最后心跳时间',
  `register_time` datetime DEFAULT NULL COMMENT 'WVP注册时间',
  `media_server_id` varchar(100) DEFAULT NULL COMMENT 'WVP流媒体服务器ID',
  `encode_dev_index_code` varchar(100) DEFAULT NULL COMMENT '海康编码设备索引码',
  `device_capability_set` varchar(100) DEFAULT NULL COMMENT '海康设备能力集编码',
  `device_sn` varchar(100) DEFAULT NULL COMMENT '大华设备序列号',
  `device_category` int DEFAULT NULL COMMENT '大华设备类别',
  `device_type` varchar(50) DEFAULT NULL COMMENT '大华设备类型',
  `owner_code` varchar(100) DEFAULT NULL COMMENT '大华所属者编码',
  `is_online` varchar(10) DEFAULT NULL COMMENT '大华在线状态: 0/1',
  `sleep_stat` int DEFAULT NULL COMMENT '大华休眠状态: 0-非休眠/1-休眠',
  `third_proxy_port` int DEFAULT NULL COMMENT '大华第三方代理端口',
  `third_proxy_server_code` varchar(100) DEFAULT NULL COMMENT '大华第三方代理服务器编码',
  `license_limit` int DEFAULT NULL COMMENT '大华license限制',
  `offline_reason` varchar(200) DEFAULT NULL COMMENT '大华离线原因',
  `sub_system` varchar(100) DEFAULT NULL COMMENT '大华子系统标识',
  `units_info` text COMMENT '大华单元信息（JSON）包含unitType等',
  `ext_field1` varchar(500) DEFAULT NULL COMMENT '扩展字段1',
  `ext_field2` varchar(500) DEFAULT NULL COMMENT '扩展字段2',
  `ext_field3` text COMMENT '扩展字段3（JSON）',
  `create_id` varchar(100) DEFAULT NULL COMMENT '创建者ID',
  `update_id` varchar(100) DEFAULT NULL COMMENT '更新者ID',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_device_instance` (`device_id`,`instance_key`),
  UNIQUE KEY `uk_instance_platform_device` (`instance_key`,`platform_device_id`),
  KEY `idx_instance_key` (`instance_key`),
  KEY `idx_device_sn` (`device_sn`),
  KEY `idx_encode_dev_index_code` (`encode_dev_index_code`),
  KEY `idx_media_server_id` (`media_server_id`),
  CONSTRAINT `fk_video_device_ext` FOREIGN KEY (`device_id`) REFERENCES `video_platform_device` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='视频平台设备扩展表(设备级特有字段)';

CREATE TABLE `video_platform_instance` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `platform_type` varchar(50) NOT NULL COMMENT '平台类型：wvp/ics/icc',
  `instance_key` varchar(100) NOT NULL COMMENT '实例唯一标识',
  `name` varchar(200) NOT NULL COMMENT '实例名称',
  `endpoint` varchar(500) NOT NULL COMMENT '平台API地址或域',
  `auth` text COMMENT '鉴权配置（JSON）',
  `version` varchar(50) DEFAULT NULL COMMENT '平台版本',
  `options` text COMMENT '其他选项配置（JSON）',
  `auto_create_products` tinyint DEFAULT '0' COMMENT 'WVP是否自动创建GB/级联产品：0-否，1-是',
  `enabled` tinyint DEFAULT '1' COMMENT '是否启用：0-禁用，1-启用',
  `creator_id` varchar(100) DEFAULT NULL COMMENT '创建者ID',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_instance_key` (`instance_key`),
  KEY `idx_platform_type` (`platform_type`),
  KEY `idx_enabled` (`enabled`),
  KEY `idx_creator_id` (`creator_id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='视频平台实例表';